from enum import Enum, auto

global_props = None

# Development
DEBUG = False

# Dimensions
DEF_BLOCK_SIZE = 50
DEF_BLOCK_WIDTH = 100
DEF_GAP = 40
DEF_VBAR_SIZE = 4000

### Temporary 
DEF_NUM_COMPONENTS = 4
### Temporary 
DEF_NUM_MESSAGES = 200

# Factor 
DEF_WIDTH_FACTOR = 0.8
DEF_IMAGE_WIDTH_MARGIN_FACT = 0.20
DEF_IMAGE_HEIGHT_MARGIN_FACT = 0.10

DEF_RECT_WIDTH_FACT = 2
DEF_RECT_WIDTH_MARGIN_FACT = 0.60

DEF_BLOCK_TEXT_X_MARG_FACT = 0.05
DEF_BLOCK_TEXT_Y_MARG_FACT = 0.10

DEF_DETAILS_OFFSET_X_MARG_FACT = 0.25

# UX
DEF_SCROLL_SPEED_FACT = 20

# Modes
class Mode(Enum):
    INTERACTIVE = auto()
    PNG = auto()
    SVG = auto()
    HTML = auto()