global_props = None

DEF_BLOCK_SIZE = 50
DEF_BLOCK_WIDTH = 100
DEF_GAP = 15
DEF_VBAR_SIZE = 4000

# temporary
DEF_NUM_COMPONENTS = 4

DEF_WIDTH_FACTOR = 0.8
DEF_RECT_WIDTH_FACT = 2

DEF_BLOCK_TEXT_X_MARG_FACT = 0.05
DEF_BLOCK_TEXT_Y_MARG_FACT = 0.2

# UX
DEF_SCROLL_SPEED_FACT = 20